version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARG_LINUX_LOCALE: en_US.UTF-8
        ARG_USER_UID: ${ARG_USER_UID}
        ARG_USER_GID: ${ARG_USER_GID}
        ARG_GO_VERSION: 1.21.5
    container_name: golang-app
    working_dir: /home/user/project
    extra_hosts:
      - dockerhost:host-gateway
    ports:
      - 4200:4200
      - 3002:3002
    tty: true
    volumes:
      - app_local:/usr/local
      - ~/.zsh_history:/home/user/.bash_history
      - .:/home/user/project
volumes:
  app_local:
